// Generated by design-token-bridge-mcp
/** @type {import('tailwindcss').Config} */
export default {
  "theme": {
    "extend": {
      "colors": {
        "primary": "#7c3aed",
        "primary-light": "#a78bfa",
        "primary-dark": "#5b21b6",
        "secondary": "#06b6d4",
        "secondary-light": "#22d3ee",
        "accent": "#f59e0b",
        "background": "#0f172a",
        "surface": "#1e293b",
        "surface-light": "#334155",
        "text": "#f8fafc",
        "text-muted": "#94a3b8",
        "text-accent": "#cbd5e1",
        "error": "#ef4444",
        "success": "#10b981",
        "border": "#334155"
      },
      "fontSize": {
        "display-large": [
          "3.75rem",
          {
            "lineHeight": "4.25rem",
            "fontWeight": "800"
          }
        ],
        "display": [
          "3rem",
          {
            "lineHeight": "3.5rem",
            "fontWeight": "700"
          }
        ],
        "heading": [
          "1.875rem",
          {
            "lineHeight": "2.25rem",
            "fontWeight": "700"
          }
        ],
        "subheading": [
          "1.5rem",
          {
            "lineHeight": "2rem",
            "fontWeight": "600"
          }
        ],
        "body-large": [
          "1.125rem",
          {
            "lineHeight": "1.75rem",
            "fontWeight": "400"
          }
        ],
        "body": [
          "1rem",
          {
            "lineHeight": "1.5rem",
            "fontWeight": "400"
          }
        ],
        "body-small": [
          "0.875rem",
          {
            "lineHeight": "1.25rem",
            "fontWeight": "400"
          }
        ],
        "caption": [
          "0.75rem",
          {
            "lineHeight": "1rem",
            "fontWeight": "500"
          }
        ]
      },
      "fontFamily": {
        "inter": [
          "Inter",
          "sans-serif"
        ]
      },
      "spacing": {
        "xs": "0.25rem",
        "sm": "0.5rem",
        "md": "1rem",
        "lg": "1.5rem",
        "xl": "2rem",
        "2xl": "3rem",
        "3xl": "4rem",
        "4xl": "6rem"
      },
      "borderRadius": {
        "sm": "4px",
        "md": "8px",
        "lg": "12px",
        "xl": "16px",
        "2xl": "24px",
        "full": "9999px"
      },
      "boxShadow": {
        "sm": "0px 1px 3px #0000004d",
        "md": "0px 4px 12px #00000040",
        "lg": "0px 8px 30px #7C3AED33",
        "glow": "0px 0px 40px #7C3AED4d"
      }
    }
  }
};

