import type { DesignTokens } from "../types/tokens.js";

/**
 * Generate SwiftUI theme files from universal tokens.
 * Optionally includes Liquid Glass modifiers for iOS 26+.
 */
export function generateSwiftUITheme(
  tokens: DesignTokens,
  liquidGlass: boolean = false
): string {
  const sections: string[] = [];

  sections.push("// Generated by design-token-bridge-mcp");
  sections.push("// Do not edit manually — regenerate from design tokens\n");
  sections.push("import SwiftUI\n");

  // Colors
  if (tokens.colors) {
    sections.push("// MARK: - Colors\n");
    sections.push("extension Color {");
    for (const [name, token] of Object.entries(tokens.colors)) {
      const swiftName = toCamelCase(name);
      const { r, g, b } = hexToRGB(token.value);
      sections.push(
        `    static let ${swiftName} = Color(red: ${r}, green: ${g}, blue: ${b})`
      );
    }
    sections.push("}\n");
  }

  // Typography
  if (tokens.typography) {
    sections.push("// MARK: - Typography\n");
    sections.push("struct AppTypography {");
    for (const [name, token] of Object.entries(tokens.typography)) {
      const swiftName = toCamelCase(name);
      const weight = mapSwiftFontWeight(token.fontWeight);
      sections.push(
        `    static let ${swiftName} = Font.system(size: ${token.fontSize}, weight: ${weight})`
      );
    }
    sections.push("}\n");

    // View modifier for easy application
    sections.push("extension View {");
    for (const [name, token] of Object.entries(tokens.typography)) {
      const swiftName = toCamelCase(name);
      const weight = mapSwiftFontWeight(token.fontWeight);
      sections.push(`    func ${swiftName}Style() -> some View {`);
      sections.push(
        `        self.font(.system(size: ${token.fontSize}, weight: ${weight}))`
      );
      sections.push("    }");
    }
    sections.push("}\n");
  }

  // Spacing
  if (tokens.spacing) {
    sections.push("// MARK: - Spacing\n");
    sections.push("struct AppSpacing {");
    for (const [name, value] of Object.entries(tokens.spacing)) {
      const swiftName = toCamelCase(name);
      sections.push(`    static let ${swiftName}: CGFloat = ${value}`);
    }
    sections.push("}\n");
  }

  // Radii
  if (tokens.radii) {
    sections.push("// MARK: - Corner Radii\n");
    sections.push("struct AppRadii {");
    for (const [name, value] of Object.entries(tokens.radii)) {
      const swiftName = toCamelCase(name);
      sections.push(`    static let ${swiftName}: CGFloat = ${value}`);
    }
    sections.push("}\n");
  }

  // Elevation
  if (tokens.elevation) {
    sections.push("// MARK: - Shadows\n");
    sections.push("extension View {");
    for (const [name, token] of Object.entries(tokens.elevation)) {
      const swiftName = toCamelCase(name);
      const { r, g, b } = hexToRGB(token.shadowColor);
      sections.push(`    func ${swiftName}Shadow() -> some View {`);
      sections.push(
        `        self.shadow(color: Color(red: ${r}, green: ${g}, blue: ${b}).opacity(${token.shadowOpacity}), radius: ${token.shadowRadius}, x: ${token.shadowOffset.x}, y: ${token.shadowOffset.y})`
      );
      sections.push("    }");
    }
    sections.push("}\n");
  }

  // Liquid Glass (iOS 26+)
  if (liquidGlass && tokens.colors) {
    sections.push("// MARK: - Liquid Glass (iOS 26+)\n");
    sections.push("@available(iOS 26.0, *)");
    sections.push("extension View {");

    // Find primary color for tinting
    const primaryEntry = Object.entries(tokens.colors).find(([name]) =>
      name.toLowerCase().includes("primary")
    );

    if (primaryEntry) {
      const swiftName = toCamelCase(primaryEntry[0]);
      sections.push("    func brandedGlassEffect() -> some View {");
      sections.push(
        `        self.glassEffect(.regular.tint(.${swiftName}))`
      );
      sections.push("    }");
    }

    sections.push("    func subtleGlassEffect() -> some View {");
    sections.push("        self.glassEffect(.regular)");
    sections.push("    }");
    sections.push("}\n");

    // Glass card component
    sections.push("@available(iOS 26.0, *)");
    sections.push("struct GlassCard<Content: View>: View {");
    sections.push("    let content: Content\n");
    sections.push("    init(@ViewBuilder content: () -> Content) {");
    sections.push("        self.content = content()");
    sections.push("    }\n");
    sections.push("    var body: some View {");

    const radius = tokens.radii
      ? Object.values(tokens.radii).sort((a, b) => a - b)[Math.floor(Object.values(tokens.radii).length / 2)] ?? 16
      : 16;

    sections.push("        content");
    sections.push(`            .padding(${tokens.spacing ? Object.values(tokens.spacing).sort((a, b) => a - b)[Math.floor(Object.values(tokens.spacing).length / 2)] ?? 16 : 16})`);
    sections.push(`            .clipShape(RoundedRectangle(cornerRadius: ${radius}))`);
    sections.push("            .glassEffect(.regular)");
    sections.push("    }");
    sections.push("}\n");
  }

  return sections.join("\n");
}

function toCamelCase(str: string): string {
  const parts = str.split(/[-_\s]/);
  return (
    parts[0].toLowerCase() +
    parts
      .slice(1)
      .map((s) => s.charAt(0).toUpperCase() + s.slice(1).toLowerCase())
      .join("")
  );
}

function hexToRGB(hex: string): { r: string; g: string; b: string } {
  let h = hex.replace("#", "");
  if (h.length === 3) {
    h = h[0] + h[0] + h[1] + h[1] + h[2] + h[2];
  }
  const r = (parseInt(h.slice(0, 2), 16) / 255).toFixed(3);
  const g = (parseInt(h.slice(2, 4), 16) / 255).toFixed(3);
  const b = (parseInt(h.slice(4, 6), 16) / 255).toFixed(3);
  return { r, g, b };
}

function mapSwiftFontWeight(weight?: number): string {
  if (!weight) return ".regular";
  const map: Record<number, string> = {
    100: ".ultraLight",
    200: ".thin",
    300: ".light",
    400: ".regular",
    500: ".medium",
    600: ".semibold",
    700: ".bold",
    800: ".heavy",
    900: ".black",
  };
  return map[weight] ?? ".regular";
}
