import type { DesignTokens } from "../types/tokens.js";

/**
 * Generate CSS custom properties from universal tokens.
 */
export function generateCSSVariables(
  tokens: DesignTokens,
  darkTokens?: DesignTokens
): string {
  const lines: string[] = [];
  lines.push("/* Generated by design-token-bridge-mcp */\n");

  // Light / default theme
  lines.push(":root {");
  lines.push(...generateVarBlock(tokens, "  "));
  lines.push("}\n");

  // Dark theme
  if (darkTokens) {
    lines.push("@media (prefers-color-scheme: dark) {");
    lines.push("  :root {");
    lines.push(...generateVarBlock(darkTokens, "    "));
    lines.push("  }");
    lines.push("}\n");

    lines.push('[data-theme="dark"] {');
    lines.push(...generateVarBlock(darkTokens, "  "));
    lines.push("}\n");
  }

  return lines.join("\n");
}

function generateVarBlock(tokens: DesignTokens, indent: string): string[] {
  const lines: string[] = [];

  if (tokens.colors) {
    lines.push(`${indent}/* Colors */`);
    for (const [name, token] of Object.entries(tokens.colors)) {
      lines.push(`${indent}--color-${name}: ${token.value.toLowerCase()};`);
    }
    lines.push("");
  }

  if (tokens.typography) {
    lines.push(`${indent}/* Typography */`);
    for (const [name, token] of Object.entries(tokens.typography)) {
      lines.push(`${indent}--font-size-${name}: ${token.fontSize}px;`);
      if (token.lineHeight) {
        lines.push(`${indent}--line-height-${name}: ${token.lineHeight}px;`);
      }
      if (token.fontWeight) {
        lines.push(`${indent}--font-weight-${name}: ${token.fontWeight};`);
      }
      if (token.fontFamily) {
        lines.push(`${indent}--font-family-${name}: ${token.fontFamily};`);
      }
      if (token.letterSpacing) {
        lines.push(`${indent}--letter-spacing-${name}: ${token.letterSpacing}px;`);
      }
    }
    lines.push("");
  }

  if (tokens.spacing) {
    lines.push(`${indent}/* Spacing */`);
    for (const [name, value] of Object.entries(tokens.spacing)) {
      lines.push(`${indent}--space-${name}: ${value}px;`);
    }
    lines.push("");
  }

  if (tokens.radii) {
    lines.push(`${indent}/* Border Radius */`);
    for (const [name, value] of Object.entries(tokens.radii)) {
      lines.push(`${indent}--radius-${name}: ${value}px;`);
    }
    lines.push("");
  }

  if (tokens.elevation) {
    lines.push(`${indent}/* Shadows */`);
    for (const [name, token] of Object.entries(tokens.elevation)) {
      const { shadowOffset, shadowRadius, shadowColor, shadowOpacity } = token;
      const alpha = Math.round(shadowOpacity * 255)
        .toString(16)
        .padStart(2, "0");
      lines.push(
        `${indent}--shadow-${name}: ${shadowOffset.x}px ${shadowOffset.y}px ${shadowRadius}px ${shadowColor.toLowerCase()}${alpha};`
      );
    }
    lines.push("");
  }

  if (tokens.motion) {
    lines.push(`${indent}/* Motion */`);
    for (const [name, token] of Object.entries(tokens.motion)) {
      lines.push(`${indent}--duration-${name}: ${token.duration}ms;`);
      lines.push(`${indent}--easing-${name}: ${token.easing};`);
    }
    lines.push("");
  }

  return lines;
}
